# Generated by Django 3.2 on 2021-08-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
