# Generated by Django 3.2 on 2021-04-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
