# Generated by Django 3.2 on 2021-05-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactApi', '0003_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='contactApi.contact'),
        ),
    ]
